### ISSUE TITLE
Link to documentation not working

### ISSUE THREAD

**Issue by DataExplorerUser** [davewd/sho#41]
Hi Dave,

I saw your post on reddit/r/python. Interesting project!

The link to the documentation on https://github.com/davewd/sho seems to not work unfortunately. It's linking to 
https://sho.readthedocs.io/ which results in a 'Sorry, this page does not exist message.'.

**Comment by davewd** [comment]
Appreciate it. Thanks.

**Comment by davewd** [comment]
Resolved: https://sho.readthedocs.io/en/latest/usage.html

Thanks for the highlight.  If there are any extra docs you want (its relatively sparse so far) please let me know in a new issue.

Appreciate medium article clap / reddit upvotes !

Thanks.
